<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
=======
<<<<<<< HEAD
s
=======
=======

>>>>>>> 7c54f14 (Chore:Update Cargo)
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
<<<<<<< HEAD
atk >= = ">= 2.28" 
atk-sys = "v0.18.0" 
>>>>>>> 851dcee (Update cargo.toml)
>>>>>>> 9fde6ab (Chore:Update Cargo)
=======
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 

>>>>>>> 7c54f14 (Chore:Update Cargo)
=======
>>>>>>> a5655d4 (Chore:Rebase patch01 master)
