<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 90f3613 (Chore:Rebase master)
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> f0e3735 (Chore:Add AUTHORS)
=======
<<<<<<< HEAD
>>>>>>> 7d837f7 (Chore:Update directory)
=======
<<<<<<< HEAD
>>>>>>> 2a594fd (Chore:Update Cargo)
=======
<<<<<<< HEAD
>>>>>>> 03f5714 (Chore:Update directory)
=======
<<<<<<< HEAD
>>>>>>> 5ad3e0d (Chore:Update Cargo)
=======
<<<<<<< HEAD
>>>>>>> d9e7628 (Chore:Rebase patch01 master)
=======
=======
>>>>>>> 61a47de (Chore:Update directory)
=======
>>>>>>> 3cdea5e (Chore:Rebase master)
<<<<<<< HEAD
=======
=======
>>>>>>> 58bf9c0 (Chore:Resolve Merge Conflicts)
=======
>>>>>>> 8ffacc5 (Chore:Rebase master)
=======
>>>>>>> 90f3613 (Chore:Rebase master)

=======
=======
>>>>>>> 9f4bfa6 (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
s
=======
<<<<<<< HEAD
>>>>>>> 9f12a31 (Update Cargo.toml)
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> e8c2350 (Chore:Update cargo)
<<<<<<< HEAD
>>>>>>> bd663f2 (Chore:Update cargo)
=======
=======
=======
>>>>>>> 90f3613 (Chore:Rebase master)
=======
=======

>>>>>>> 57b9364 (Chore:Resolve Merge Conflicts)
>>>>>>> 9f4bfa6 (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 58bf9c0 (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
>>>>>>> 61a47de (Chore:Update directory)
=======
=======
=======
>>>>>>> ea61c03 (Chore:Rebase master)
>>>>>>> 8ffacc5 (Chore:Rebase master)
>>>>>>> 3cdea5e (Chore:Rebase master)
=======
>>>>>>> 86d94cd (Chore:Update directory)
=======
=======
>>>>>>> ea61c03 (Chore:Rebase master)
>>>>>>> da06c0e (Chore:Rebase master)
>>>>>>> 90f3613 (Chore:Rebase master)
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
<<<<<<< HEAD
futures = "0.3"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
atk = "0.18.0" 
<<<<<<< HEAD
=======
atk-sys = ">= 0.18.0" 
=======
=======
>>>>>>> 3617d9e (Update cargo.toml)
=======
>>>>>>> 69bbc46 (Chore:Add AUTHORS)
<<<<<<< HEAD
s
=======
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]

<<<<<<< HEAD

[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
atk = "0.18.0" 
=======
atk = ">= 0.1.0" 
>>>>>>> a0cf675 (Update Cargo.toml)
=======
atk = "0.18.0" 
>>>>>>> e0ee37d (Update cargo.toml)
atk-sys = ">= 0.18.0" 
>>>>>>> a0cf675 (Update Cargo.toml)
=======
atk >= = ">= 2.28" 
=======
atk = ">= 2.28" 
<<<<<<< HEAD
>>>>>>> ed11267 (Update cargo.toml)
atk-sys = "v0.18.0" 
>>>>>>> 4d9a9da (Update cargo.toml)
<<<<<<< HEAD
>>>>>>> 9780232 (Chore:Update cargo)
=======
=======
atk-sys = ">= 0.18.0" 
>>>>>>> 2e85963 (Update cargo.toml)
=======
s
>>>>>>> 255ed2f (Update cargo.toml)
<<<<<<< HEAD
>>>>>>> 3617d9e (Update cargo.toml)
<<<<<<< HEAD
>>>>>>> d4552c8 (Update Cargo.toml)
=======
=======
=======
=======
>>>>>>> c346404 (Chore:Update Cargo)
=======
>>>>>>> d29b0f5 (Chore:Update Cargo)
<<<<<<< HEAD
s
=======
<<<<<<< HEAD
>>>>>>> fd9fc1e (Chore:Update Cargo)
=======
=======
<<<<<<< HEAD
>>>>>>> 9fde6ab (Chore:Update Cargo)
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> a0cf675 (Update Cargo.toml)
=======
>>>>>>> 787d5a68c01e9ec278f3cac2e8ca6f31317d178a
>>>>>>> bd563a7 (Chore:Add AUTHORS)
>>>>>>> 69bbc46 (Chore:Add AUTHORS)
<<<<<<< HEAD
>>>>>>> f0e3735 (Chore:Add AUTHORS)
=======
=======
>>>>>>> 766a893 (Update README.md)
<<<<<<< HEAD
>>>>>>> 7d837f7 (Chore:Update directory)
=======
=======
>>>>>>> 7ba5151 (Chore:Update Cargo)
>>>>>>> fd9fc1e (Chore:Update Cargo)
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 2a594fd (Chore:Update Cargo)
=======
=======
<<<<<<< HEAD
>>>>>>> 7ba5151 (Chore:Update Cargo)
=======
=======
=======
<<<<<<< HEAD
>>>>>>> 7ba5151 (Chore:Update Cargo)
=======
>>>>>>> 381da28 (Chore:Update directory)
=======
<<<<<<< HEAD
s
=======
=======
=======
>>>>>>> 55e1698 (Chore:Rebase patch01 master)

[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
<<<<<<< HEAD
<<<<<<< HEAD
atk >= = ">= 2.28" 
atk-sys = "v0.18.0" 
>>>>>>> 851dcee (Update cargo.toml)
>>>>>>> 9fde6ab (Chore:Update Cargo)
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> c346404 (Chore:Update Cargo)
<<<<<<< HEAD
>>>>>>> 03f5714 (Chore:Update directory)
=======
=======
>>>>>>> c346404 (Chore:Update Cargo)
>>>>>>> 381da28 (Chore:Update directory)
=======
=======
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 

>>>>>>> 7c54f14 (Chore:Update Cargo)
>>>>>>> d29b0f5 (Chore:Update Cargo)
<<<<<<< HEAD
>>>>>>> 5ad3e0d (Chore:Update Cargo)
=======
=======
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 

>>>>>>> 55e1698 (Chore:Rebase patch01 master)
<<<<<<< HEAD
>>>>>>> d9e7628 (Chore:Rebase patch01 master)
=======
=======
=======
=======
futures = "0.3"
<<<<<<< HEAD
<<<<<<< HEAD
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
<<<<<<< HEAD
<<<<<<< HEAD

>>>>>>> b3d100b (Chore:Update cargo)
=======
atk = ">= 0.1.0" 
=======
atk = "0.18.0" 
>>>>>>> 9f4bfa6 (Chore:Resolve Merge Conflicts)
atk-sys = ">= 0.18.0" 
<<<<<<< HEAD
=======
s
>>>>>>> 255ed2f (Update cargo.toml)
>>>>>>> b41c519 (Update Cargo.toml)
<<<<<<< HEAD
>>>>>>> 9f12a31 (Update Cargo.toml)
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> e8c2350 (Chore:Update cargo)
<<<<<<< HEAD
>>>>>>> bd663f2 (Chore:Update cargo)
=======
=======
=======
>>>>>>> b3d100b (Chore:Update cargo)
=======
=======

>>>>>>> 57b9364 (Chore:Resolve Merge Conflicts)
>>>>>>> 9f4bfa6 (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
>>>>>>> 58bf9c0 (Chore:Resolve Merge Conflicts)
>>>>>>> 61a47de (Chore:Update directory)
=======
futures = "0.3"
>>>>>>> 86d94cd (Chore:Update directory)
=======
=======
>>>>>>> 9b513a3 (Chore:Update Merge Conflicts)
=======
=======
<<<<<<< HEAD
s
=======
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
>>>>>>> 4801d3a (Chore:Rebase master)
<<<<<<< HEAD
>>>>>>> d2feec9 (Chore:Update cargo)
<<<<<<< HEAD
>>>>>>> b3d100b (Chore:Update cargo)
=======
=======
=======
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
=======
<<<<<<< HEAD
s
=======
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
>>>>>>> c1475d1 (Chore:Rebase master)
>>>>>>> da06c0e (Chore:Rebase master)
>>>>>>> 90f3613 (Chore:Rebase master)
