<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
=======
=======
>>>>>>> 3617d9e (Update cargo.toml)
=======
>>>>>>> 69bbc46 (Chore:Add AUTHORS)
<<<<<<< HEAD
s
=======
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
atk = "0.18.0" 
=======
atk = ">= 0.1.0" 
>>>>>>> a0cf675 (Update Cargo.toml)
=======
atk = "0.18.0" 
>>>>>>> e0ee37d (Update cargo.toml)
atk-sys = ">= 0.18.0" 
>>>>>>> a0cf675 (Update Cargo.toml)
=======
atk >= = ">= 2.28" 
=======
atk = ">= 2.28" 
<<<<<<< HEAD
>>>>>>> ed11267 (Update cargo.toml)
atk-sys = "v0.18.0" 
>>>>>>> 4d9a9da (Update cargo.toml)
<<<<<<< HEAD
>>>>>>> 9780232 (Chore:Update cargo)
=======
=======
atk-sys = ">= 0.18.0" 
>>>>>>> 2e85963 (Update cargo.toml)
=======
s
>>>>>>> 255ed2f (Update cargo.toml)
<<<<<<< HEAD
>>>>>>> 3617d9e (Update cargo.toml)
=======
=======
=======
>>>>>>> c346404 (Chore:Update Cargo)
<<<<<<< HEAD
s
=======
<<<<<<< HEAD
>>>>>>> fd9fc1e (Chore:Update Cargo)
=======
=======
<<<<<<< HEAD
>>>>>>> 9fde6ab (Chore:Update Cargo)
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> a0cf675 (Update Cargo.toml)
=======
>>>>>>> 787d5a68c01e9ec278f3cac2e8ca6f31317d178a
>>>>>>> bd563a7 (Chore:Add AUTHORS)
>>>>>>> 69bbc46 (Chore:Add AUTHORS)
=======
>>>>>>> 766a893 (Update README.md)
=======
>>>>>>> 7ba5151 (Chore:Update Cargo)
>>>>>>> fd9fc1e (Chore:Update Cargo)
=======
<<<<<<< HEAD
>>>>>>> 7ba5151 (Chore:Update Cargo)
=======
=======
<<<<<<< HEAD
s
=======
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk >= = ">= 2.28" 
atk-sys = "v0.18.0" 
>>>>>>> 851dcee (Update cargo.toml)
>>>>>>> 9fde6ab (Chore:Update Cargo)
>>>>>>> c346404 (Chore:Update Cargo)
