[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.19.1"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "^0"
