<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
atk = "0.18.0" 
futures = "0.3"
atk = ">= 0.1.0" 
atk-sys = ">= 0.18.0" 
cxx-qt = "0.6.1"
=======
<<<<<<< HEAD
s
=======
=======
>>>>>>> 7ba5151 (Chore:Update Cargo)
=======

>>>>>>> 7c54f14 (Chore:Update Cargo)
=======
=======
<<<<<<< HEAD
<<<<<<< HEAD
s
=======
>>>>>>> 9f12a31 (Update Cargo.toml)
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
<<<<<<< HEAD
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
<<<<<<< HEAD
=======

>>>>>>> 7c54f14 (Chore:Update Cargo)
=======
>>>>>>> a5655d4 (Chore:Rebase patch01 master)
=======
atk = ">= 0.1.0" 
atk-sys = ">= 0.18.0" 
=======
s
>>>>>>> 255ed2f (Update cargo.toml)
>>>>>>> b41c519 (Update Cargo.toml)
>>>>>>> 9f12a31 (Update Cargo.toml)
