[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
<<<<<<< HEAD
futures = "0.3"
=======
futures = "0.3"
<<<<<<< HEAD
<<<<<<< HEAD
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
<<<<<<< HEAD
<<<<<<< HEAD

=======
atk = ">= 0.1.0" 
=======
atk = "0.18.0" 
>>>>>>> 9f4bfa6 (Chore:Resolve Merge Conflicts)
atk-sys = ">= 0.18.0" 
<<<<<<< HEAD
=======
s
>>>>>>> 255ed2f (Update cargo.toml)
>>>>>>> b41c519 (Update Cargo.toml)
<<<<<<< HEAD
>>>>>>> 9f12a31 (Update Cargo.toml)
=======
=======

>>>>>>> 57b9364 (Chore:Resolve Merge Conflicts)
>>>>>>> 9f4bfa6 (Chore:Resolve Merge Conflicts)
=======
>>>>>>> 9b513a3 (Chore:Update Merge Conflicts)
=======
=======
<<<<<<< HEAD
s
=======
[package]
name = "Beginners"
version = "0.1.0"
edition = "2021"
authors = ["Kiyini Joseph Balamazze"]


[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git" }
trunk = "0.20.3"
actix = { version = "0.13.3" }
chrono = "0.4"
futures = "0.3"
atk = "0.18.0" 
atk-sys = ">= 0.18.0" 
>>>>>>> 4801d3a (Chore:Rebase master)
>>>>>>> d2feec9 (Chore:Update cargo)
