<<<<<<< HEAD
<<<<<<< HEAD
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
=======
>>>>>>> 39affb5 (Add files via upload)
=======
>>>>>>> 818d650 (Add files via upload)
=======
=======
>>>>>>> 7ba5151 (Chore:Update Cargo)
=======
<<<<<<< HEAD
>>>>>>> f0e3735 (Chore:Add AUTHORS)
=======
<<<<<<< HEAD
>>>>>>> 2a594fd (Chore:Update Cargo)
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
<<<<<<< HEAD

[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
=======
>>>>>>> 787d5a68c01e9ec278f3cac2e8ca6f31317d178a
<<<<<<< HEAD
>>>>>>> bd563a7 (Chore:Add AUTHORS)
=======
=======
<<<<<<< HEAD
=======
=======
>>>>>>> d18c8f8 (Chore:Add AUTHORS.)
=======
>>>>>>> 69bbc46 (Chore:Add AUTHORS)
<<<<<<< HEAD
>>>>>>> f0e3735 (Chore:Add AUTHORS)
=======
=======
>>>>>>> fd9fc1e (Chore:Update Cargo)
>>>>>>> 2a594fd (Chore:Update Cargo)
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
<<<<<<< HEAD

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 22cca21 (Add files via upload)
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"
<<<<<<< HEAD

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
=======
<<<<<<< HEAD
>>>>>>> 6dd7d7b (Chore:Resolve Merge Conflicts)
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

<<<<<<< HEAD
[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
<<<<<<< HEAD

>>>>>>> 820281c (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
>>>>>>> 7ba5151 (Chore:Update Cargo)
=======
=======
>>>>>>> dfa7665 (Chore:Rebase patch01 master)
<<<<<<< HEAD
>>>>>>> a5655d4 (Chore:Rebase patch01 master)
=======
=======
>>>>>>> 2b9416e (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
>>>>>>> d87cd10 (Chore:Resolve Merge Conflicts)
=======
=======
>>>>>>> 6dd7d7b (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
>>>>>>> ea61c03 (Chore:Rebase master)
=======
=======
>>>>>>> 3118847 (Update Projects:ToDoEmailApp)
<<<<<<< HEAD
>>>>>>> a9cd9ea (Chore:Rebase master)
=======
=======
=======
=======
>>>>>>> 34118f8 (Chore:Update Cargo)
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
<<<<<<< HEAD
<<<<<<< HEAD

[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
=======
>>>>>>> 787d5a68c01e9ec278f3cac2e8ca6f31317d178a
>>>>>>> bd563a7 (Chore:Add AUTHORS)
>>>>>>> d18c8f8 (Chore:Add AUTHORS.)
=======
>>>>>>> 34118f8 (Chore:Update Cargo)
=======
>>>>>>> 39affb5 (Add files via upload)
<<<<<<< HEAD
>>>>>>> 22cca21 (Add files via upload)
<<<<<<< HEAD
>>>>>>> 57def2a (Add files via upload)
=======
=======
=======
>>>>>>> 818d650 (Add files via upload)
<<<<<<< HEAD
>>>>>>> a9f995b (Add files via upload)
<<<<<<< HEAD
>>>>>>> 0803e58 (Add files via upload)
=======
=======
=======
=======
>>>>>>> 7ba5151 (Chore:Update Cargo)
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
<<<<<<< HEAD

[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
=======
>>>>>>> 787d5a68c01e9ec278f3cac2e8ca6f31317d178a
<<<<<<< HEAD
>>>>>>> bd563a7 (Chore:Add AUTHORS)
<<<<<<< HEAD
>>>>>>> 69bbc46 (Chore:Add AUTHORS)
<<<<<<< HEAD
>>>>>>> f0e3735 (Chore:Add AUTHORS)
=======
=======
=======
=======
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"

<<<<<<< HEAD
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"
<<<<<<< HEAD

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"

>>>>>>> 820281c (Chore:Resolve Merge Conflicts)
<<<<<<< HEAD
>>>>>>> 7ba5151 (Chore:Update Cargo)
<<<<<<< HEAD
>>>>>>> fd9fc1e (Chore:Update Cargo)
<<<<<<< HEAD
>>>>>>> 2a594fd (Chore:Update Cargo)
=======
=======
=======
=======
>>>>>>> dfa7665 (Chore:Rebase patch01 master)
<<<<<<< HEAD
>>>>>>> a5655d4 (Chore:Rebase patch01 master)
<<<<<<< HEAD
>>>>>>> 55e1698 (Chore:Rebase patch01 master)
<<<<<<< HEAD
>>>>>>> d9e7628 (Chore:Rebase patch01 master)
=======
=======
=======
=======
>>>>>>> 2b9416e (Chore:Resolve Merge Conflicts)
>>>>>>> d87cd10 (Chore:Resolve Merge Conflicts)
>>>>>>> 62121c2 (Chore:Update cargo)
>>>>>>> 381da28 (Chore:Update directory)
