[package]
name = "todo_email_app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
   lettre = { version = "0.10.0-rc.4", features = ["smtp-tokio", "builder"] }
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"

